on:
  workflow_dispatch:

env:
      TF_VAR_location: 'WestEurope'
      TF_BACKEND_STORAGE_ACCOUNT_NAME: 'terraformtestnthub'
      TF_BACKEND_CONTAINER_NAME: 'terraformtestnthub'
      TF_BACKEND_KEY: 'terraform.tfstate'
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    
jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
        - name: 'Checkout'
          uses: actions/checkout@v4
            
        - name: 'Setup Terraform'
          uses: hashicorp/setup-terraform@v2
    
        - name: 'Terraform Init'
          run: terraform init -backend-config="storage_account_name=${{ env.TF_BACKEND_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ env.TF_BACKEND_CONTAINER_NAME }}" -backend-config="key=${{ env.TF_BACKEND_KEY }}" -backend-config="access_key=${{ secrets.TF_BACKEND_CONTAINER_NAME }}"
        - name: Terraform Destroy
          run: terraform destroy -auto-approve


